repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.3.0
    hooks:
      - id: mypy
        args: [--no-strict-optional, --ignore-missing-imports]
        files: ^(app/|tests/)
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        name: black
        types: [ python ]
        files: ^(app/|tests/)
  - repo: https://github.com/hadialqattan/pycln
    rev: v2.1.3
    hooks:
      - id: pycln
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        types: [ python ]
        files: ^(app/|tests/)
        exclude: '.*/migrations/.*'
        args: [
            '--multi-line=3',
            '--force-grid-wrap=0',
            '--trailing-comma',
            '--use-parentheses',
            '--ensure-newline-before-comments',
        ]
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        name: flake8
        types: [ python ]
        files: ^(app/|tests/)
        args: [
            '--max-line-length=88',
            '--extend-ignore=E203'
        ]